services:
  - type: web
    name: keyzone
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: KEYZONE
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_LOCALE
        value: fr
      - key: APP_FALLBACK_LOCALE
        value: fr
      - key: APP_FAKER_LOCALE
        value: fr_FR
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: noreply@keyzone.fr
      - key: MAIL_FROM_NAME
        value: KEYZONE
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
