databases:
  - name: keyzone-db
    plan: free
    databaseName: keyzone
    user: keyzone_user
    region: frankfurt

services:
  - type: web
    name: keyzone
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: KEYZONE
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:RBNgoa1wug5yJgYZm118vegpfddZdULOlHCWCUA7SWI=
      - key: APP_URL
        value: https://keyzone.onrender.com
      - key: APP_LOCALE
        value: fr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: keyzone-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: keyzone-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: keyzone-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: keyzone-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: keyzone-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: noreply@keyzone.fr
      - key: MAIL_FROM_NAME
        value: KEYZONE
      - key: LOG_CHANNEL
        value: stderr
