services:
  - type: web
    name: keyzone
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: KEYZONE
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:RBNgoa1wug5yJgYZm118vegpfddZdULOlHCWCUA7SWI=
      - key: APP_LOCALE
        value: fr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.prfodcjukvgnkbncwesm
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: noreply@keyzone.fr
      - key: MAIL_FROM_NAME
        value: KEYZONE
